language: c
dist: trusty
sudo: required

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - bc
    - doxygen
    - expect
    - gettext
    - libncurses5-dev
    - tree

env:
  global:
    - OMF_REPO_URI="https://github.com/$TRAVIS_REPO_SLUG"
    - OMF_REPO_BRANCH="$TRAVIS_BRANCH"

before_install:
  - source tools/travis-github-pr-integration.sh
  - tools/travis-install-fish.sh

before_script:
  - tree -h
  - export
  - fish $TRAVIS_BUILD_DIR/bin/install

script:
  - tests/run.fish
  - pushd pkg/fish-spec; fish -c 'fish-spec'; popd
  - pushd pkg/omf; fish -c 'fish-spec'; popd
  - tests/test-generate-themes-doc.fish

after_failure:
  - pwd
  - cd ~/.config/fish; tree -h; find . -type f | xargs cat

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: fHR34H901zaBpUdm9BECQfocnPki8HdigH9CQxopvJ6Rm0WCLzCst4zPESAlO/Jb1t6OYtU6Goqmdq3yqzo8+moCrygrpMUtzIel/TDhkLzC2SIlmMdnw2/Xdwzisd/8QBVwu9ns8xJ2C4eegolNazNsc1Ow/wULaLwA7vUJrfcSmvYBepfe3MPSX/KLU3BBRhiTr3RhuzV+D1qQcSrAiWGVr4zWUiRAar6WD1D4athZO9OX33upBYpraGEa3sRWrUJjVv7KWMH566Y2MSAtd0NBgsF9dn3S5nKTXtfyGXt2gkykZ9Ag1B7B9AR9BHpn5UcvDdn7FZpEREfrllkDU8iG67RD7owyRl/T5jyWQecU2Q9Rlco5esEpbkY7sXmzwj2RVBGzsaVjxajZ+C7Ns2ogMcP8o+xqfcUASXjlJM2kJQRSenwx82Vq6uQ0vbhgKWBTQE1qsEkLDCthUxQ9eJ0/exoBp95wrZinilmEyps00oqmS40HEhB+JmuN2sGVWhpSczVDvVmdV+XSewLqfRnWtr2yhL8dR1sfVm2lJh3Dzik4BFUASByeBJnViU4dDilLlb4S3Dwk0XZh9HGwLs9ujNA3PT23uoRu4VRBQkIwXZE8v/qvf4/7w8IowofzezYcjwxkaqu1hNgTKNOkbgopV9RdwrUxy4f53S0l2jY=
